### ISSUE TITLE
Sometimes empty top level .zattrs file?

### ISSUE THREAD

**Issue by PaulHax** [spatial-image/multiscale-spatial-image#42]
I suspect that this [gist](https://gist.github.com/thewtex/4654540b41fa9344b1ec1d60e61a8421) produced a top level .zattrs file containing only `{}`.  Expected NGFF attributes, ie `"multiscales": [ ...`

@thewtex

**Comment by thewtex** [comment]
Resolved via https://github.com/spatial-image/multiscale-spatial-image/pull/59/commits/aef02bb1ea879ec7ef1d04b5facfe696a86d9cef in https://github.com/spatial-image/multiscale-spatial-image/pull/59/
