### ISSUE TITLE
xarray DataTree

### ISSUE THREAD

**Issue by TomNicholas** [spatial-image/multiscale-spatial-image#8]
Hi there, I was just wondering if you had seen the prototype [xarray DataTree](https://github.com/TomNicholas/datatree) we're working on? Supporting multi-scale image arrays is supposed to be one of the use cases so if you have any thoughts I would love to hear them!

**Comment by joshmoore** [comment]
@thewtex: writing here what I would have said last night on the zarr call had we not ran out of time:
 - had a good chat with Tom _et al._ re: https://github.com/zarr-developers/zarr-specs/issues/125
 - he pointed out that [dataclasses](https://github.com/astropenguin/xarray-dataclasses) plays a related role to `spatial-image`
 - and that assuming dataclasses can be mixed with datatrees(!) that the combination could play a similar role to `spatial-image-multiscale`
 - (in a separate email, he mentioned [xarray accessors](https://xarray.pydata.org/en/stable/internals/extending-xarray.html) but we didn't chat about that)
 - all along way to say that you might be an ideal candidate (a) for testing out prototypes and (b) identifying functionality that you'd like to see added upstream :wink:

**Comment by thewtex** [comment]
Hi @TomNicholas @joshmoore ,

Thank you for the tips!! :pray: 

Yes, I will move forward with these excellent suggestions!

Current plans (thoughts welcome):

1. Investigate how we can create tests to validate adherence to the OME-NGFF spec
2. Update the [SpatialImage](https://github.com/spatial-image/spatial-image/blob/ad657ab33a2c4a56461635efec4c974d6cb88f94/spatial_image.py#L16) type alias to a data class with further type specification
3. and that assuming dataclasses can be mixed with datatrees(!) that the combination could play a similar role to spatial-image-multiscale <- this =-)
4. add features to update output the OME-NGFF to the v0.4 spec

> (in a separate email, he mentioned xarray accessors but we didn't chat about that)

It is later down the line, but I am interested in your thoughts on how we could possibly use this to make `itk.Image` more compatible with xarray.

**Comment by thewtex** [comment]
> Investigate how we can create tests to validate adherence to the OME-NGFF spec

The `ngff` repository now makes JSON schema validation possible per:

- https://github.com/ome/ngff/blob/main/.github/workflows/validation.yml
- https://github.com/ome/ngff/issues/58

Future, additional array validation is being added per:

- https://github.com/ome/ome-zarr-py/issues/102
- https://github.com/ome/ome-zarr-py/pull/142

> Update the SpatialImage type alias to a data class with further type specification

Draft: https://github.com/spatial-image/spatial-image/pull/8

**Comment by thewtex** [comment]
Draft implementation based on xarray DataTree in https://github.com/spatial-image/spatial-image-multiscale/pull/10

SpatialImage was rebuilt on xarray dataclasses in https://github.com/spatial-image/spatial-image/pull/8 and the constructor was refactored to correspond to the NGFF v0.4 data model. Todo: Add support for additional dimension orders.

**Comment by thewtex** [comment]
Channel-first support added in [spatial-image 0.2.0](https://github.com/spatial-image/spatial-image/releases/tag/v0.2.0)

**Comment by thewtex** [comment]
Full initial implementation in #11 

To come: more examples

**Comment by thewtex** [comment]
NGFF 0.4 validation in https://github.com/spatial-image/spatial-image-multiscale/pull/18

**Comment by thewtex** [comment]
Basic docs: in #20

**Comment by TomNicholas** [comment]
Glad you were able to update to update to accommodate those breaking changes in datatree so quickly @wtex - let me know if you have any particular issues or suggestions!

**Comment by thewtex** [comment]
@TomNicholas if you please review / merge / cut a release with https://github.com/xarray-contrib/datatree/pull/90 that would be very helpful!

This is a blocker to create demos e.g. re #32 and related to https://github.com/thewtex/shardedstore . With these demos @joshmoore this is worthwhile discussing with the zarr community.

**Comment by thewtex** [comment]
@TomNicholas again for your help with this!

We moved to the recently migrated DataTree in multiscale-spatial-image 2.0.0: https://github.com/spatial-image/multiscale-spatial-image/releases
