### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by goanpeca** [spatial-image/multiscale-spatial-image#85]
Hello team :)

While working on https://github.com/conda-forge/multiscale-spatial-image-feedstock/pull/1

I noticed that the source code is importing `zarr`. Should it be added to the requirements then?

Cheers 🚀

**Comment by thewtex** [comment]
Hello @goanpeca :wave: 

> While working on conda-forge/multiscale-spatial-image-feedstock#1

Thank you!

> I noticed that the source code is importing zarr. Should it be added to the requirements then?

Yes! Added here: https://github.com/spatial-image/multiscale-spatial-image/pull/86
