### ISSUE TITLE
Add `rgb` argument to `to_multiscale()`

### ISSUE THREAD

**Issue by LucaMarconato** [spatial-image/multiscale-spatial-image#92]
The `rgb` argument was added to the `to_spatial_image()` function in this PR: https://github.com/spatial-image/spatial-image/pull/21/files.

In order to provide a consistent behavior for multiscale-spatial-image, I think we should add the `rgb` option also to `to_multiscale()`.

CC @giovp @aeisenbarth

**Comment by aeisenbarth** [comment]
Good point! I would agree for consistency, but I am not sure whether it is necessary.

In SpatialData, [`to_multiscale`](https://github.com/scverse/spatialdata/blob/b80b364b56feaa42f317e1cca05e3a3db02f7475/src/spatialdata/models/models.py#L197) is only invoked from an existing SpatialImage, which has been initialized with  `c_coords` and `rgb` arguments (hidden in kwargs). In this scenario, `to_multiscale` can use the SpatialImage DataArray as it is and does not need to handle RGB.

Actually the [interface doesn't even accept](https://github.com/spatial-image/multiscale-spatial-image/blob/38d824cd0f718b76cbddabc6ee71705e17515238/multiscale_spatial_image/to_multiscale/to_multiscale.py#L30) `c_coords` (for which `rgb` is [syntactic sugar](https://github.com/spatial-image/spatial-image/blob/8bc3c54d6d8595f6ba217e97cf5e35f4716ab5bc/spatial_image.py#L1235-L1237)). That means every user of `to_multiscale` must go through `to_spatial_image` first. As I see it, at the moment, there is no issue to solve.
